version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
    - name: sales
      identifier: raw_gz_sales
      description: sales of Greenweez
      tests:
        - unique:
            column_name: "(orders_id || '-' || pdt_id)"
    - name: product
      identifier: raw_gz_product
      columns:
        - name: products_id
          description: Primary key of the table
          tests:
            - unique
            - not_null
    - name: ship
      identifier: raw_gz_ship
      columns:
        - name: orders_id
          description: Primary key of the table
          tests:
            - unique
            - not_null